<a href="https://colab.research.google.com/github/Guille20241/CDE/blob/main/TAREACALIFICADA2_Grupo8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<center><img src="https://i.imgur.com/zRrFdsf.png" width="700"></center>


# **Tarea Calificada 2**

**Grupo 8**
1. JORD√ÅN ALVARADO, GUILLERMO SEBASTIAN - 20244659
2. PFOCCO DAVALOS, JOSUE - 20191946
3. MOCHCCO SANCA, RUBY - 20143018

# **Importar data**

In [85]:
import pandas as pd
import numpy as np

url = 'https://docs.google.com/spreadsheets/d/e/2PACX-1vSPVJIoDhupNyUpYD65FSHt6kMmF_KaxE2RD6CV1FOMP4vVw7WfKQMqpqo0ieD9vhMAmYP1NpBmw0od/pub?gid=658985149&single=true&output=csv'

df=pd.read_csv(url)#path del csv del dataset

In [86]:
df

,Back,Table 1. Human Development Index and its components,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,SDG3,NaN,SDG4.3,NaN,SDG4.4,NaN,SDG8.5,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,Human Development Index (HDI),NaN,Life expectancy at birth,NaN,Expected years of schooling,NaN,Mean years of schooling,NaN,Gross national income (GNI) per capita,NaN,GNI per capita rank minus HDI rank,NaN,HDI rank
4,HDI rank,Country,Value,NaN,(years),NaN,(years),NaN,(years),NaN,(2017 PPP $),NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
271,NaN,Column 2: UNDESA (2022a).,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
272,NaN,"Column 3: CEDLAS and World Bank (2022), ICF Ma...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
273,NaN,"Column 4: Barro and Lee (2018), ICF Macro Demo...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
274,NaN,"Column 5: IMF (2022), UNDESA (2022b), United N...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
275,NaN,Column 6: Calculated based on data in columns ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# **1. Very High Human Development**

In [87]:
#definir el detaframe VHD
VHD = pd.read_csv(url, skiprows=7, nrows=66)
#mantener las columnas con datos y eliminar las que tienen espacios vac√≠os
VHD=VHD.drop(columns=['Unnamed: 3','Unnamed: 5','Unnamed: 7','Unnamed: 9','Unnamed: 11','Unnamed: 13'])
#asegurarnos que los datos en cada columna no posean espacios en blanco al inicio y al final
VHD=VHD.applymap(lambda x: x.strip() if isinstance(x,str) else x)
#renombramos las columnas de inter√©s
VHD=VHD.rename(columns={"Unnamed: 0":"HDIRank","VERY HIGH HUMAN DEVELOPMENT":"Country","Unnamed: 2":"HDI","Unnamed: 4":"lexp","Unnamed: 6":"expyscho","Unnamed: 8":"meanyscho","Unnamed: 10":"GNI","Unnamed: 12":"GNI-HDI","Unnamed: 14":"HDIRank2020"})
#verificar si hay paises duplicados
len(set(VHD['Country']))
#son 66, no hay duplicados

66

In [88]:
#verificamos el tipo de valores que poseen las columnas
VHD.info()
#la columna GNI es del tipo object por poseer elementos str, deber√≠a ser num√©rica

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 66 entries, 0 to 65
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   HDIRank      66 non-null     int64
 1   Country      66 non-null     object
 2   HDI          66 non-null     int64
 3   lexp         66 non-null     float64
 4   expyscho     66 non-null     float64
 5   meanyscho    66 non-null     float64
 6   GNI          66 non-null     object
 7   GNI-HDI      66 non-null     int64
 8   HDIRank2020  66 non-null     int64
dtypes: float64(3), int64(4), object(2)
memory usage: 4.8+ KB

In [89]:
#verificaremos cuales columnas tienen missing values
VHD[VHD.isna().any(axis=1)]
#no hay missing value

Empty DataFrame
Columns: [HDIRank, Country, HDI, lexp, expyscho, meanyscho, GNI, GNI-HDI, HDIRank2020]
Index: []

In [90]:
#valores extra√±os que posee GNI usando el regex '(\W)' que indica todos los elementos menos palabras y n√∫meros, se convierte en lista y se le resta el simbolo "."
set(VHD['GNI'].str.extractall('(\W)').loc[:,0].to_list())-set('.')
#hay comas

{','}

In [91]:
#reemplazamos cada coma por "" en GNI
VHD['GNI']=VHD['GNI'].str.replace(",",'')
#convertimes GNI a num√©rico, los errores se ignoran
VHD['GNI']=VHD['GNI'].apply(lambda col:pd.to_numeric(col,errors='ignore'))
#verificamos que las columnas correspondientes sean num√©ricas
VHD.info()
#dtype ok

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 66 entries, 0 to 65
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   HDIRank      66 non-null     int64
 1   Country      66 non-null     object
 2   HDI          66 non-null     int64
 3   lexp         66 non-null     float64
 4   expyscho     66 non-null     float64
 5   meanyscho    66 non-null     float64
 6   GNI          66 non-null     int64
 7   GNI-HDI      66 non-null     int64
 8   HDIRank2020  66 non-null     int64
dtypes: float64(3), int64(5), object(1)
memory usage: 4.8+ KB

In [92]:
#identificamos los countries con simbolos extra√±os
VHD[VHD['Country'].str.contains(r"\w*[\u00C0-\u01DA']\w*")]

,HDIRank,Country,HDI,lexp,expyscho,meanyscho,GNI,GNI-HDI,HDIRank2020
47,48,T√ºrkiye,838,76.0,18.3,8.6,31033,-3,48

In [93]:
#reemplazamos por Turkey
VHD.loc[47, 'Country'] = 'Turkey'
print(VHD.loc[47,'Country'])

Turkey

In [94]:
#Uppercase a todas las cells de Country
VHD['Country']=VHD.Country.str.upper()

In [95]:
#estadistica de VHD
VHD.describe()

,HDIRank,HDI,lexp,expyscho,meanyscho,GNI,GNI-HDI,HDIRank2020
count,66.000000,66.000000,66.000000,66.000000,66.000000,66.000000,66.000000,66.000000
mean,33.318182,880.545455,78.736364,16.263636,11.890909,41792.848485,0.969697,33.393939
std,19.119188,52.980746,4.134085,1.901144,1.476871,17852.776880,12.636905,19.225687
min,1.000000,800.000000,69.400000,12.300000,7.300000,14664.000000,-42.000000,1.000000
25%,17.250000,831.250000,75.400000,15.200000,11.025000,27625.000000,-3.000000,17.000000
50%,33.500000,881.500000,79.100000,16.150000,12.250000,39190.500000,4.500000,33.500000
75%,49.750000,929.750000,82.450000,17.225000,12.900000,52853.500000,9.000000,49.000000
max,66.000000,962.000000,85.500000,21.100000,14.100000,90919.000000,18.000000,67.000000

In [96]:
VHD.insert(VHD.shape[1], "Clasificacion",  pd.Series(['very_high_human_development' for x in range(VHD.shape[0])]) )

In [97]:
VHD

,HDIRank,Country,HDI,lexp,expyscho,meanyscho,GNI,GNI-HDI,HDIRank2020,Clasificacion
0,1,SWITZERLAND,962,84.0,16.5,13.9,66933,5,3,very_high_human_development
1,2,NORWAY,961,83.2,18.2,13.0,64660,6,1,very_high_human_development
2,3,ICELAND,959,82.7,19.2,13.8,55782,11,2,very_high_human_development
3,4,"HONG KONG, CHINA (SAR)",952,85.5,17.3,12.2,62607,6,4,very_high_human_development
4,5,AUSTRALIA,951,84.5,21.1,12.7,49238,18,5,very_high_human_development
...,...,...,...,...,...,...,...,...,...,...
61,62,MALAYSIA,803,74.9,13.3,10.6,26658,-8,61,very_high_human_development
62,63,GEORGIA,802,71.7,15.6,12.8,14664,17,64,very_high_human_development
63,63,MAURITIUS,802,73.6,15.2,10.4,22025,-1,62,very_high_human_development
64,63,SERBIA,802,74.2,14.4,11.4,19123,4,62,very_high_human_development
65,66,THAILAND,800,78.7,15.9,8.7,17030,6,64,very_high_human_development

# **2. High human development**

In [98]:
HD=pd.read_csv(url, skiprows=74, nrows=49)
HD=HD.drop(columns=['Unnamed: 3','Unnamed: 5','Unnamed: 7','Unnamed: 9','Unnamed: 11','Unnamed: 13'])
HD=HD.applymap(lambda x: x.strip() if isinstance(x,str) else x)
HD=HD.rename(columns={"Unnamed: 0":"HDIRank","HIGH HUMAN DEVELOPMENT":"Country","Unnamed: 2":"HDI","Unnamed: 4":"lexp","Unnamed: 6":"expyscho","Unnamed: 8":"meanyscho","Unnamed: 10":"GNI","Unnamed: 12":"GNI-HDI","Unnamed: 14":"HDIRank2020"})
len(set(HD['Country']))
#son 49, no hay duplicados

49

In [99]:
HD.info()
#dtype ok

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49 entries, 0 to 48
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   HDIRank      49 non-null     int64
 1   Country      49 non-null     object
 2   HDI          49 non-null     int64
 3   lexp         49 non-null     float64
 4   expyscho     49 non-null     float64
 5   meanyscho    49 non-null     float64
 6   GNI          49 non-null     object
 7   GNI-HDI      49 non-null     int64
 8   HDIRank2020  49 non-null     int64
dtypes: float64(3), int64(4), object(2)
memory usage: 3.6+ KB

In [100]:
#reemplazamos cada coma por "" en GNI
HD['GNI']=HD['GNI'].str.replace(",",'')
#convertimes GNI a num√©rico, los errores se ignoran
HD['GNI']=HD['GNI'].apply(lambda col:pd.to_numeric(col,errors='ignore'))
#verificamos que las columnas correspondientes sean num√©ricas
HD.info()
#dtype ok

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49 entries, 0 to 48
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   HDIRank      49 non-null     int64
 1   Country      49 non-null     object
 2   HDI          49 non-null     int64
 3   lexp         49 non-null     float64
 4   expyscho     49 non-null     float64
 5   meanyscho    49 non-null     float64
 6   GNI          49 non-null     int64
 7   GNI-HDI      49 non-null     int64
 8   HDIRank2020  49 non-null     int64
dtypes: float64(3), int64(5), object(1)
memory usage: 3.6+ KB

In [101]:
HD[HD.isna().any(axis=1)]
#no hay missing values

Empty DataFrame
Columns: [HDIRank, Country, HDI, lexp, expyscho, meanyscho, GNI, GNI-HDI, HDIRank2020]
Index: []

In [102]:
HD[HD['Country'].str.contains(r"\w*[\u00C0-\u01DA']\w*")]
#no hay Countries con simbolos raros

Empty DataFrame
Columns: [HDIRank, Country, HDI, lexp, expyscho, meanyscho, GNI, GNI-HDI, HDIRank2020]
Index: []

In [103]:
#Uppercase a todas las cells de Country
HD['Country']=HD.Country.str.upper()

In [104]:
#estadistica de HD
HD.describe()

,HDIRank,HDI,lexp,expyscho,meanyscho,GNI,GNI-HDI,HDIRank2020
count,49.000000,49.000000,49.000000,49.000000,49.000000,49.000000,49.000000,49.000000
mean,90.693878,746.877551,72.093878,14.012245,9.806122,13232.122449,1.816327,90.816327
std,14.259798,28.452177,3.509832,1.324549,1.380279,4283.215652,16.052873,14.621151
min,67.000000,703.000000,62.300000,10.600000,7.300000,5308.000000,-47.000000,64.000000
25%,79.000000,720.000000,70.300000,13.100000,8.700000,10588.000000,-8.000000,79.000000
50%,91.000000,745.000000,72.000000,13.900000,9.800000,12948.000000,4.000000,90.000000
75%,102.000000,768.000000,73.800000,14.700000,10.900000,14875.000000,11.000000,103.000000
max,115.000000,796.000000,79.900000,18.700000,12.500000,25831.000000,37.000000,117.000000

In [105]:
HD.insert(HD.shape[1], "Clasificacion",  pd.Series(['high_human_development' for x in range(HD.shape[0])]) )

In [106]:
HD

,HDIRank,Country,HDI,lexp,expyscho,meanyscho,GNI,GNI-HDI,HDIRank2020,Clasificacion
0,67,ALBANIA,796,76.5,14.4,11.3,14131,17,68,high_human_development
1,68,BULGARIA,795,71.8,13.9,11.4,23079,-8,64,high_human_development
2,68,GRENADA,795,74.9,18.7,9.0,13484,18,70,high_human_development
3,70,BARBADOS,790,77.6,15.7,9.9,12306,26,71,high_human_development
4,71,ANTIGUA AND BARBUDA,788,78.5,14.2,9.3,16792,2,71,high_human_development
5,72,SEYCHELLES,785,71.3,13.9,10.3,25831,-17,69,high_human_development
6,73,SRI LANKA,782,76.4,14.1,10.8,12578,21,75,high_human_development
7,74,BOSNIA AND HERZEGOVINA,780,75.3,13.8,10.5,15242,4,73,high_human_development
8,75,SAINT KITTS AND NEVIS,777,71.7,15.4,8.7,23358,-16,76,high_human_development
9,76,IRAN (ISLAMIC REPUBLIC OF),774,73.9,14.6,10.6,13001,15,77,high_human_development
10,77,UKRAINE,773,71.6,15.0,11.1,13256,11,78,high_human_development
11,78,NORTH MACEDONIA,770,73.8,13.6,10.2,15918,-3,79,high_human_development
12,79,CHINA,768,78.2,14.2,7.6,17504,-8,82,high_human_development
13,80,DOMINICAN REPUBLIC,767,72.6,14.5,9.3,17990,-11,82,high_human_development
14,80,MOLDOVA (REPUBLIC OF),767,68.8,14.4,11.8,14875,-1,81,high_human_development
15,80,PALAU,767,66.0,15.8,12.5,13819,5,80,high_human_development
16,83,CUBA,764,73.7,14.4,12.5,7879,37,73,high_human_development
17,84,PERU,762,72.4,15.4,9.9,12246,13,85,high_human_development
18,85,ARMENIA,759,72.0,13.1,11.3,13158,4,87,high_human_development
19,86,MEXICO,758,70.2,14.9,9.2,17896,-16,88,high_human_development
20,87,BRAZIL,754,72.8,15.6,8.1,14370,-5,86,high_human_development
21,88,COLOMBIA,752,72.8,14.4,8.9,14384,-7,88,high_human_development
22,89,SAINT VINCENT AND THE GRENADINES,751,69.6,14.7,10.8,11961,11,82,high_human_development
23,90,MALDIVES,747,79.9,12.6,7.3,15448,-14,97,high_human_development
24,91,ALGERIA,745,76.4,14.6,8.1,10800,13,96,high_human_development
25,91,AZERBAIJAN,745,69.4,13.5,10.5,14257,-8,100,high_human_development
26,91,TONGA,745,71.0,16.0,11.4,6822,34,90,high_human_development
27,91,TURKMENISTAN,745,69.3,13.2,11.3,13021,-1,93,high_human_development
28,95,ECUADOR,740,73.7,14.6,8.8,10312,11,99,high_human_development
29,96,MONGOLIA,739,71.0,15.0,9.4,10588,9,90,high_human_development
30,97,EGYPT,731,70.2,13.8,9.6,11732,4,97,high_human_development
31,97,TUNISIA,731,73.8,15.4,7.4,10258,10,94,high_human_development
32,99,FIJI,730,67.1,14.7,10.9,9980,9,94,high_human_development
33,99,SURINAME,730,70.3,13.0,9.8,12672,-6,92,high_human_development
34,101,UZBEKISTAN,727,70.9,12.5,11.9,7917,18,107,high_human_development
35,102,DOMINICA,720,72.8,13.3,8.1,11488,0,106,high_human_development
36,102,JORDAN,720,74.3,10.6,10.4,9924,8,104,high_human_development
37,104,LIBYA,718,71.9,12.9,7.6,15336,-27,117,high_human_development
38,105,PARAGUAY,717,70.3,13.0,8.9,12349,-10,100,high_human_development
39,106,"PALESTINE, STATE OF",715,73.5,13.4,9.9,6583,21,109,high_human_development
40,106,SAINT LUCIA,715,71.1,12.9,8.5,12048,-7,104,high_human_development
41,108,GUYANA,714,65.7,12.5,8.6,22465,-47,107,high_human_development
42,109,SOUTH AFRICA,713,62.3,13.6,11.4,12948,-17,102,high_human_development
43,110,JAMAICA,709,70.5,13.4,9.2,8834,4,110,high_human_development
44,111,SAMOA,707,72.8,12.4,11.4,5308,24,112,high_human_development
45,112,GABON,706,65.8,13.0,9.4,13367,-25,113,high_human_development
46,112,LEBANON,706,75.0,11.3,8.7,9526,-1,103,high_human_development
47,114,INDONESIA,705,67.6,13.7,8.6,11466,-11,116,high_human_development
48,115,VIET NAM,703,73.6,13.0,8.4,7867,6,113,high_human_development

# **3. Medium Human Development**

In [107]:
MD=pd.read_csv(url, skiprows=124, nrows=44)
MD=MD.drop(columns=['Unnamed: 3','Unnamed: 5','Unnamed: 7','Unnamed: 9','Unnamed: 11','Unnamed: 13'])
MD=MD.applymap(lambda x: x.strip() if isinstance(x,str) else x)
MD=MD.rename(columns={"Unnamed: 0":"HDIRank","MEDIUM HUMAN DEVELOPMENT":"Country","Unnamed: 2":"HDI","Unnamed: 4":"lexp","Unnamed: 6":"expyscho","Unnamed: 8":"meanyscho","Unnamed: 10":"GNI","Unnamed: 12":"GNI-HDI","Unnamed: 14":"HDIRank2020"})
len(set(MD['Country']))
#son 44, no hay duplicados

44

In [108]:
MD.info()
#GNI deber√≠a ser num√©rico

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 44 entries, 0 to 43
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   HDIRank      44 non-null     int64
 1   Country      44 non-null     object
 2   HDI          44 non-null     int64
 3   lexp         44 non-null     float64
 4   expyscho     44 non-null     float64
 5   meanyscho    44 non-null     float64
 6   GNI          44 non-null     object
 7   GNI-HDI      44 non-null     int64
 8   HDIRank2020  44 non-null     int64
dtypes: float64(3), int64(4), object(2)
memory usage: 3.2+ KB

In [109]:
MD[MD.isna().any(axis=1)]
#no hay missing value

Empty DataFrame
Columns: [HDIRank, Country, HDI, lexp, expyscho, meanyscho, GNI, GNI-HDI, HDIRank2020]
Index: []

In [110]:
set(MD['GNI'].str.extractall('(\W)').loc[:,0].to_list())-set('.')
#hay comas

{','}

In [111]:
MD['GNI']=MD['GNI'].str.replace(",",'')
MD['GNI']=MD['GNI'].apply(lambda col:pd.to_numeric(col,errors='ignore'))
MD.info()
#dtype ok

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 44 entries, 0 to 43
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   HDIRank      44 non-null     int64
 1   Country      44 non-null     object
 2   HDI          44 non-null     int64
 3   lexp         44 non-null     float64
 4   expyscho     44 non-null     float64
 5   meanyscho    44 non-null     float64
 6   GNI          44 non-null     int64
 7   GNI-HDI      44 non-null     int64
 8   HDIRank2020  44 non-null     int64
dtypes: float64(3), int64(5), object(1)
memory usage: 3.2+ KB

In [112]:
#identificamos los countries con simbolos extra√±os
MD[MD['Country'].str.contains(r"\w*[\u00C0-\u01DA']\w*")]

,HDIRank,Country,HDI,lexp,expyscho,meanyscho,GNI,GNI-HDI,HDIRank2020
24,140,Lao People's Democratic Republic,607,68.1,10.1,5.4,7700,-18,142
43,159,C√¥te d'Ivoire,550,58.6,10.7,5.2,5217,-22,159

In [113]:
#reemplazamos por Lao Peoples Democratic Republic and Ivory Coast
MD.loc[24, 'Country'] ='Lao Peoples Democratic Republic'
MD.loc[43, 'Country'] ='Ivory Coast'
print(MD.loc[24,'Country'])
print(MD.loc[43,'Country'])

Lao Peoples Democratic Republic
Ivory Coast

In [114]:
MD['Country']=MD.Country.str.upper()

In [115]:
MD.describe()

,HDIRank,HDI,lexp,expyscho,meanyscho,GNI,GNI-HDI,HDIRank2020
count,44.000000,44.000000,44.000000,44.000000,44.000000,44.000000,44.000000,44.000000
mean,137.340909,623.545455,66.775000,11.811364,7.143182,5727.613636,-0.909091,137.159091
std,12.835168,46.216102,4.671145,1.342371,1.954410,2807.498118,16.163148,13.254123
min,116.000000,550.000000,57.100000,9.200000,4.700000,659.000000,-47.000000,110.000000
25%,126.750000,585.750000,63.475000,10.700000,5.550000,3976.000000,-9.000000,126.750000
50%,137.500000,619.500000,67.650000,11.950000,6.700000,4943.000000,1.500000,137.500000
75%,148.250000,666.250000,70.425000,12.725000,8.075000,7397.000000,9.250000,148.250000
max,159.000000,699.000000,74.100000,14.900000,11.400000,16198.000000,26.000000,159.000000

In [116]:
MD.insert(MD.shape[1], "Clasificacion",  pd.Series(['medium_human_development' for x in range(MD.shape[0])]) )
MD

,HDIRank,Country,HDI,lexp,expyscho,meanyscho,GNI,GNI-HDI,HDIRank2020,Clasificacion
0,116,PHILIPPINES,699,69.3,13.1,9.0,8920,-3,113,medium_human_development
1,117,BOTSWANA,693,61.1,12.3,10.3,16198,-43,110,medium_human_development
2,118,BOLIVIA (PLURINATIONAL STATE OF),692,63.6,14.9,9.8,8111,0,119,medium_human_development
3,118,KYRGYZSTAN,692,70.0,13.2,11.4,4566,26,121,medium_human_development
4,120,VENEZUELA (BOLIVARIAN REPUBLIC OF),691,70.6,12.8,11.1,4811,20,118,medium_human_development
5,121,IRAQ,686,70.4,12.1,7.9,9977,-12,122,medium_human_development
6,122,TAJIKISTAN,685,71.6,11.7,11.3,4548,23,126,medium_human_development
7,123,BELIZE,683,70.5,13.0,8.8,6309,6,120,medium_human_development
8,123,MOROCCO,683,74.0,14.2,5.9,7303,1,122,medium_human_development
9,125,EL SALVADOR,675,70.7,12.7,7.2,8296,-8,124,medium_human_development
10,126,NICARAGUA,667,73.8,12.6,7.1,5625,6,129,medium_human_development
11,127,BHUTAN,666,71.8,13.2,5.2,9438,-15,125,medium_human_development
12,128,CABO VERDE,662,74.1,12.6,6.3,6230,2,127,medium_human_development
13,129,BANGLADESH,661,72.4,12.4,7.4,5472,4,128,medium_human_development
14,130,TUVALU,641,64.5,9.4,10.6,6351,-2,131,medium_human_development
15,131,MARSHALL ISLANDS,639,65.3,10.2,10.9,4620,12,131,medium_human_development
16,132,INDIA,633,67.2,11.9,6.7,659,-6,130,medium_human_development
17,133,GHANA,632,63.8,12.0,8.3,5745,-2,135,medium_human_development
18,134,MICRONESIA (FEDERATED STATES OF),628,70.7,11.5,7.8,3696,22,136,medium_human_development
19,135,GUATEMALA,627,69.2,10.6,5.7,8723,-20,133,medium_human_development
20,136,KIRIBATI,624,67.4,11.8,8.0,4063,14,137,medium_human_development
21,137,HONDURAS,621,70.1,10.1,7.1,5298,-1,138,medium_human_development
22,138,SAO TOME AND PRINCIPE,618,67.6,13.4,6.2,4021,13,139,medium_human_development
23,139,NAMIBIA,615,59.3,11.9,7.2,8634,-23,134,medium_human_development
24,140,LAO PEOPLES DEMOCRATIC REPUBLIC,607,68.1,10.1,5.4,7700,-18,142,medium_human_development
25,140,TIMOR-LESTE,607,67.7,12.6,5.4,4461,7,140,medium_human_development
26,140,VANUATU,607,70.4,11.5,7.1,3085,23,142,medium_human_development
27,143,NEPAL,602,68.4,12.9,5.1,3877,10,144,medium_human_development
28,144,ESWATINI (KINGDOM OF),597,57.1,13.7,5.6,7679,-21,141,medium_human_development
29,145,EQUATORIAL GUINEA,596,60.6,9.7,5.9,12074,-47,147,medium_human_development
30,146,CAMBODIA,593,69.6,11.5,5.1,4079,3,148,medium_human_development
31,146,ZIMBABWE,593,59.3,12.1,8.7,3810,9,145,medium_human_development
32,148,ANGOLA,586,61.6,12.2,5.4,5466,-14,149,medium_human_development
33,149,MYANMAR,585,65.7,10.9,6.4,3851,5,145,medium_human_development
34,150,SYRIAN ARAB REPUBLIC,577,72.1,9.2,5.1,4192,-2,152,medium_human_development
35,151,CAMEROON,576,60.3,13.1,6.2,3621,6,150,medium_human_development
36,152,KENYA,575,61.4,10.7,6.7,4474,-6,150,medium_human_development
37,153,CONGO,571,63.5,12.3,6.2,2889,11,153,medium_human_development
38,154,ZAMBIA,565,61.2,10.9,7.2,3218,7,154,medium_human_development
39,155,SOLOMON ISLANDS,564,70.3,10.3,5.7,2482,13,155,medium_human_development
40,156,COMOROS,558,63.4,11.9,5.1,3142,6,156,medium_human_development
41,156,PAPUA NEW GUINEA,558,65.4,10.4,4.7,4009,-4,157,medium_human_development
42,158,MAURITANIA,556,64.4,9.4,4.9,5075,-20,158,medium_human_development
43,159,IVORY COAST,550,58.6,10.7,5.2,5217,-22,159,medium_human_development

# **4. Low Human Development**

In [117]:
LD=pd.read_csv(url, skiprows=169, nrows=32)
LD=LD.drop(columns=['Unnamed: 3','Unnamed: 5','Unnamed: 7','Unnamed: 9','Unnamed: 11','Unnamed: 13'])
LD=LD.applymap(lambda x: x.strip() if isinstance(x,str) else x)
LD=LD.rename(columns={"Unnamed: 0":"HDIRank","LOW HUMAN DEVELOPMENT":"Country","Unnamed: 2":"HDI","Unnamed: 4":"lexp","Unnamed: 6":"expyscho","Unnamed: 8":"meanyscho","Unnamed: 10":"GNI","Unnamed: 12":"GNI-HDI","Unnamed: 14":"HDIRank2020"})
len(set(LD['Country']))
#son 32, no hay duplicados

32

In [118]:
LD.info()
#GNI deber√≠a ser num√©rico

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   HDIRank      32 non-null     int64
 1   Country      32 non-null     object
 2   HDI          32 non-null     int64
 3   lexp         32 non-null     float64
 4   expyscho     32 non-null     float64
 5   meanyscho    32 non-null     float64
 6   GNI          32 non-null     object
 7   GNI-HDI      32 non-null     int64
 8   HDIRank2020  32 non-null     int64
dtypes: float64(3), int64(4), object(2)
memory usage: 2.4+ KB

In [119]:
LD[LD.isna().any(axis=1)]
#no hay missing value

Empty DataFrame
Columns: [HDIRank, Country, HDI, lexp, expyscho, meanyscho, GNI, GNI-HDI, HDIRank2020]
Index: []

In [120]:
set(LD['GNI'].str.extractall('(\W)').loc[:,0].to_list())-set('.')
#hay comas

{','}

In [121]:
LD['GNI']=LD['GNI'].str.replace(",",'')
LD['GNI']=LD['GNI'].apply(lambda col:pd.to_numeric(col,errors='ignore'))
LD.info()
#dtype ok

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   HDIRank      32 non-null     int64
 1   Country      32 non-null     object
 2   HDI          32 non-null     int64
 3   lexp         32 non-null     float64
 4   expyscho     32 non-null     float64
 5   meanyscho    32 non-null     float64
 6   GNI          32 non-null     int64
 7   GNI-HDI      32 non-null     int64
 8   HDIRank2020  32 non-null     int64
dtypes: float64(3), int64(5), object(1)
memory usage: 2.4+ KB

In [122]:
#identificamos los countries con simbolos extra√±os
LD[LD['Country'].str.contains(r"\w*[\u00C0-\u01DA']\w*")]
#ninguno

Empty DataFrame
Columns: [HDIRank, Country, HDI, lexp, expyscho, meanyscho, GNI, GNI-HDI, HDIRank2020]
Index: []

In [123]:
LD['Country']=LD.Country.str.upper()

In [124]:
LD.describe()

,HDIRank,HDI,lexp,expyscho,meanyscho,GNI,GNI-HDI,HDIRank2020
count,32.000000,32.000000,32.00000,32.000000,32.000000,32.000000,32.000000,32.000000
mean,175.437500,483.781250,61.05625,9.518750,4.259375,2211.937500,-2.406250,175.343750
std,9.452556,46.897097,4.13201,1.612939,1.407780,1125.794141,10.063859,9.465078
min,160.000000,385.000000,52.50000,5.500000,2.100000,732.000000,-32.000000,160.000000
25%,167.500000,453.500000,59.27500,8.550000,3.175000,1351.500000,-7.250000,167.500000
50%,175.500000,495.000000,61.65000,9.700000,4.350000,2125.500000,-1.000000,175.500000
75%,183.250000,516.750000,63.97500,10.325000,5.100000,2673.000000,4.500000,183.250000
max,191.000000,549.000000,67.10000,13.000000,7.200000,5025.000000,13.000000,191.000000

In [125]:
LD.insert(LD.shape[1], "Clasificacion",  pd.Series(['low_human_development' for x in range(LD.shape[0])]) )
LD

,HDIRank,Country,HDI,lexp,expyscho,meanyscho,GNI,GNI-HDI,HDIRank2020,Clasificacion
0,160,TANZANIA (UNITED REPUBLIC OF),549,66.2,9.2,6.4,2664,7,160,low_human_development
1,161,PAKISTAN,544,66.1,8.7,4.5,4624,-19,161,low_human_development
2,162,TOGO,539,61.6,13.0,5.0,2167,12,163,low_human_development
3,163,HAITI,535,63.2,9.7,5.6,2848,2,162,low_human_development
4,163,NIGERIA,535,52.7,10.1,7.2,4790,-22,163,low_human_development
5,165,RWANDA,534,66.1,11.2,4.4,2210,6,165,low_human_development
6,166,BENIN,525,59.8,10.8,4.3,3409,-7,166,low_human_development
7,166,UGANDA,525,62.7,10.1,5.7,2181,6,166,low_human_development
8,168,LESOTHO,514,53.1,12.0,6.0,2700,-2,168,low_human_development
9,169,MALAWI,512,62.9,12.7,4.5,1466,13,169,low_human_development
10,170,SENEGAL,511,67.1,9.0,2.9,3344,-10,170,low_human_development
11,171,DJIBOUTI,509,62.3,7.4,4.1,5025,-32,171,low_human_development
12,172,SUDAN,508,65.3,7.9,3.8,3575,-14,171,low_human_development
13,173,MADAGASCAR,501,64.5,10.1,5.1,1484,8,173,low_human_development
14,174,GAMBIA,500,62.1,9.4,4.6,2172,-1,173,low_human_development
15,175,ETHIOPIA,498,65.0,9.7,3.2,2361,-5,175,low_human_development
16,176,ERITREA,492,66.5,8.1,4.9,1729,3,176,low_human_development
17,177,GUINEA-BISSAU,483,59.7,10.6,3.6,1908,0,177,low_human_development
18,178,LIBERIA,481,60.7,10.4,5.1,1289,7,179,low_human_development
19,179,CONGO (DEMOCRATIC REPUBLIC OF THE),479,59.2,9.8,7.0,1076,9,180,low_human_development
20,180,AFGHANISTAN,478,62.0,10.3,3.0,1824,-2,177,low_human_development
21,181,SIERRA LEONE,477,60.1,9.6,4.6,1622,-1,181,low_human_development
22,182,GUINEA,465,58.9,9.8,2.2,2481,-13,182,low_human_development
23,183,YEMEN,455,63.8,9.1,3.2,1314,1,183,low_human_development
24,184,BURKINA FASO,449,59.3,9.1,2.1,2118,-8,185,low_human_development
25,185,MOZAMBIQUE,446,59.3,10.2,3.2,1198,2,184,low_human_development
26,186,MALI,428,58.9,7.4,2.3,2133,-11,186,low_human_development
27,187,BURUNDI,426,61.7,10.7,3.1,732,4,187,low_human_development
28,188,CENTRAL AFRICAN REPUBLIC,404,53.9,8.0,4.3,966,1,188,low_human_development
29,189,NIGER,400,61.6,7.0,2.1,1240,-3,189,low_human_development
30,190,CHAD,394,52.5,8.0,2.6,1364,-7,190,low_human_development
31,191,SOUTH SUDAN,385,55.0,5.5,5.7,768,-1,191,low_human_development

# MERGE DE TABLAS

In [128]:
# VHD, HD, MD, LD
merged_df = pd.concat([VHD, HD, MD, LD])
merged_df = merged_df.reset_index(drop=True)

In [129]:
merged_df

,HDIRank,Country,HDI,lexp,expyscho,meanyscho,GNI,GNI-HDI,HDIRank2020,Clasificacion
0,1,SWITZERLAND,962,84.0,16.5,13.9,66933,5,3,very_high_human_development
1,2,NORWAY,961,83.2,18.2,13.0,64660,6,1,very_high_human_development
2,3,ICELAND,959,82.7,19.2,13.8,55782,11,2,very_high_human_development
3,4,"HONG KONG, CHINA (SAR)",952,85.5,17.3,12.2,62607,6,4,very_high_human_development
4,5,AUSTRALIA,951,84.5,21.1,12.7,49238,18,5,very_high_human_development
...,...,...,...,...,...,...,...,...,...,...
186,187,BURUNDI,426,61.7,10.7,3.1,732,4,187,low_human_development
187,188,CENTRAL AFRICAN REPUBLIC,404,53.9,8.0,4.3,966,1,188,low_human_development
188,189,NIGER,400,61.6,7.0,2.1,1240,-3,189,low_human_development
189,190,CHAD,394,52.5,8.0,2.6,1364,-7,190,low_human_development
190,191,SOUTH SUDAN,385,55.0,5.5,5.7,768,-1,191,low_human_development

# **5. Other Countries and Territories**

In [40]:
OCT=pd.read_csv(url, skiprows=202, nrows=4)
OCT=OCT.drop(columns=['Unnamed: 3','Unnamed: 5','Unnamed: 7','Unnamed: 9','Unnamed: 11','Unnamed: 13'])
OCT=OCT.applymap(lambda x: x.strip() if isinstance(x,str) else x)
OCT=OCT.rename(columns={"Unnamed: 0":"HDIRank","OTHER COUNTRIES OR TERRITORIES":"Country","Unnamed: 2":"HDI","Unnamed: 4":"lexp","Unnamed: 6":"expyscho","Unnamed: 8":"meanyscho","Unnamed: 10":"GNI","Unnamed: 12":"GNI-HDI","Unnamed: 14":"HDIRank2020"})
len(set(OCT['Country']))
#son 4, no hay duplicados

4

In [41]:
#verificamos el tipo de valores que poseen las columnas
OCT.info()
#solo Country deber√≠a ser obj. HDIRank, HDI, expycho, meanyscho, GNI, GNI-HDI, HDIRank2020 deber√≠an tener n√∫meros

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   HDIRank      0 non-null      float64
 1   Country      4 non-null      object
 2   HDI          4 non-null      object
 3   lexp         4 non-null      float64
 4   expyscho     4 non-null      object
 5   meanyscho    4 non-null      object
 6   GNI          4 non-null      object
 7   GNI-HDI      4 non-null      object
 8   HDIRank2020  4 non-null      object
dtypes: float64(2), object(7)
memory usage: 416.0+ bytes

In [42]:
#vemos que pasa
OCT

,HDIRank,Country,HDI,lexp,expyscho,meanyscho,GNI,GNI-HDI,HDIRank2020
0,NaN,Korea (Democratic People's Rep. of),..,73.3,10.8,..,..,..,..
1,NaN,Monaco,..,85.9,..,..,..,..,..
2,NaN,Nauru,..,63.6,11.7,..,"17,730",..,..
3,NaN,Somalia,..,55.3,..,..,"1,018",..,..

In [43]:
#completamos el HDIRank con 1,2,3,4
OCT['HDIRank'] = list(range(1, len(OCT['HDIRank']) + 1))

In [44]:
#GNI tienes datos en los que en ves de "," deber√≠a ir ""
OCT['GNI']=OCT['GNI'].str.replace(",",'')

In [45]:
#Una vez que los datos a los que les corresponde ser numericos lo son, convertimos a num√©rico los elementos, sino coerce
OCT[['HDI','expyscho','meanyscho','GNI','GNI-HDI','HDIRank2020']] = OCT[['HDI','expyscho','meanyscho','GNI','GNI-HDI','HDIRank2020']].apply(pd.to_numeric, errors='coerce')
#Reemplazamos los NaN por el n√∫mero 0
OCT[['HDI','expyscho','meanyscho','GNI','GNI-HDI','HDIRank2020']]=OCT[['HDI','expyscho','meanyscho','GNI','GNI-HDI','HDIRank2020']].fillna(0)

In [46]:
OCT[OCT['Country'].str.contains(r"\w*[\u00C0-\u01DA']\w*")]

,HDIRank,Country,HDI,lexp,expyscho,meanyscho,GNI,GNI-HDI,HDIRank2020
0,1,Korea (Democratic People's Rep. of),0.0,73.3,10.8,0.0,0.0,0.0,0.0

In [47]:
#Reemplazamos por "North Korea" pq m√°s f√°cil de leer :P
OCT.loc[0, 'Country'] = 'North Korea'
print(OCT.loc[0,'Country'])

North Korea

In [48]:
OCT['Country']=OCT.Country.str.upper()

In [49]:
OCT.describe()

,HDIRank,HDI,lexp,expyscho,meanyscho,GNI,GNI-HDI,HDIRank2020
count,4.000000,4.0,4.000000,4.000000,4.0,4.000000,4.0,4.0
mean,2.500000,0.0,69.525000,5.625000,0.0,4687.000000,0.0,0.0
std,1.290994,0.0,13.163681,6.505575,0.0,8708.565668,0.0,0.0
min,1.000000,0.0,55.300000,0.000000,0.0,0.000000,0.0,0.0
25%,1.750000,0.0,61.525000,0.000000,0.0,0.000000,0.0,0.0
50%,2.500000,0.0,68.450000,5.400000,0.0,509.000000,0.0,0.0
75%,3.250000,0.0,76.450000,11.025000,0.0,5196.000000,0.0,0.0
max,4.000000,0.0,85.900000,11.700000,0.0,17730.000000,0.0,0.0

In [50]:
OCT

,HDIRank,Country,HDI,lexp,expyscho,meanyscho,GNI,GNI-HDI,HDIRank2020
0,1,NORTH KOREA,0.0,73.3,10.8,0.0,0.0,0.0,0.0
1,2,MONACO,0.0,85.9,0.0,0.0,0.0,0.0,0.0
2,3,NAURU,0.0,63.6,11.7,0.0,17730.0,0.0,0.0
3,4,SOMALIA,0.0,55.3,0.0,0.0,1018.0,0.0,0.0

# **6. Human Development Groups**

In [51]:
HDG=pd.read_csv(url, skiprows=208, nrows=4)
HDG.drop(columns=['Unnamed: 0','Unnamed: 2','Unnamed: 3','Unnamed: 5','Unnamed: 7','Unnamed: 8','Unnamed: 9','Unnamed: 11','Unnamed: 12','Unnamed: 13','Unnamed: 14'], inplace=True)

In [52]:
HDG

      Human development groups  Unnamed: 4  Unnamed: 6 Unnamed: 10
0  Very high human development        78.5        16.5      43,752
1       High human development        74.7        14.2      15,167
2     Medium human development        67.4        11.9       6,353
3        Low human development        61.3         9.5       3,009

In [53]:
HDG.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Human development groups  4 non-null      object
 1   Unnamed: 4                4 non-null      float64
 2   Unnamed: 6                4 non-null      float64
 3   Unnamed: 10               4 non-null      object
dtypes: float64(2), object(2)
memory usage: 256.0+ bytes

In [54]:
#Cambiamos el nombre de las columnas:
HDG.rename(columns={'Unnamed: 4': 'HDI',	'Unnamed: 6': 'Life_Expectancy', 'Unnamed: 10': 'GNI'}, inplace=True)

In [55]:
# reemplazamos las comas y cambiamos el formato de la √∫ltima columna
HDG['GNI'] = HDG['GNI'].str.replace(',','')
HDG['GNI']=pd.to_numeric(HDG.GNI)
HDG

      Human development groups   HDI  Life_Expectancy    GNI
0  Very high human development  78.5             16.5  43752
1       High human development  74.7             14.2  15167
2     Medium human development  67.4             11.9   6353
3        Low human development  61.3              9.5   3009

In [56]:
HDG.describe()

             HDI  Life_Expectancy           GNI
count   4.000000         4.000000      4.000000
mean   70.475000        13.025000  17070.250000
std     7.656969         3.008183  18512.305302
min    61.300000         9.500000   3009.000000
25%    65.875000        11.300000   5517.000000
50%    71.050000        13.050000  10760.000000
75%    75.650000        14.775000  22313.250000
max    78.500000        16.500000  43752.000000

# **7. Developing Countries**

In [57]:
DC=pd.read_csv(url, skiprows=213, nrows=1)
DC.drop(columns=['Unnamed: 0','Unnamed: 2','Unnamed: 3','Unnamed: 5','Unnamed: 7','Unnamed: 8','Unnamed: 9','Unnamed: 11','Unnamed: 12','Unnamed: 13','Unnamed: 14'], inplace=True)
DC

             Unnamed: 1  Unnamed: 4  Unnamed: 6 Unnamed: 10
0  Developing countries        69.9        12.3      10,704

In [58]:
DC.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Unnamed: 1   1 non-null      object
 1   Unnamed: 4   1 non-null      float64
 2   Unnamed: 6   1 non-null      float64
 3   Unnamed: 10  1 non-null      object
dtypes: float64(2), object(2)
memory usage: 160.0+ bytes

In [59]:
DC.columns = ['Countries', 'Life_Expectancy', 'Schooling', 'GNI']
DC['GNI'] = DC['GNI'].str.replace(',','')
DC['GNI']=pd.to_numeric(DC.GNI)
DC.describe()

       Life_Expectancy  Schooling      GNI
count              1.0        1.0      1.0
mean              69.9       12.3  10704.0
std                NaN        NaN      NaN
min               69.9       12.3  10704.0
25%               69.9       12.3  10704.0
50%               69.9       12.3  10704.0
75%               69.9       12.3  10704.0
max               69.9       12.3  10704.0

In [60]:
DC.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Countries        1 non-null      object
 1   Life_Expectancy  1 non-null      float64
 2   Schooling        1 non-null      float64
 3   GNI              1 non-null      int64
dtypes: float64(2), int64(1), object(1)
memory usage: 160.0+ bytes

# **8. Regions**

In [61]:
region=pd.read_csv(url, skiprows=216, nrows=6)
regionOK=region.drop(columns=['Unnamed: 0','Unnamed: 3','Unnamed: 5','Unnamed: 7','Unnamed: 9','Unnamed: 11','Unnamed: 12','Unnamed: 13','Unnamed: 14'])

In [62]:
regionOK

,Regions,Unnamed: 2,Unnamed: 4,Unnamed: 6,Unnamed: 8,Unnamed: 10
0,Arab States,708,70.9,12.4,8.0,"13,501"
1,East Asia and the Pacific,749,75.6,13.8,7.8,"15,580"
2,Europe and Central Asia,796,72.9,15.4,10.6,"19,352"
3,Latin America and the Caribbean,754,72.1,14.8,9.0,"14,521"
4,South Asia,632,67.9,11.6,6.7,"6,481"
5,Sub-Saharan Africa,547,60.1,10.3,6.0,"3,699"

In [63]:
#Limpieza de datos
#limpiando espacios
regionOK = regionOK.applymap(lambda x: x.strip() if isinstance(x, str) else x)
#cambiando el nombre de las columnas
regionOK = regionOK.rename(columns={'Unnamed: 2': 'HDI', 'Unnamed: 4': 'life',
                                    'Unnamed: 6': 'years_schooling', 'Unnamed: 8': 'Mean_schooling', 'Unnamed: 10':'GNI'})
#limpiando GNI
regionOK['GNI'] = regionOK['GNI'].str.replace(',', '')
regionOK

,Regions,HDI,life,years_schooling,Mean_schooling,GNI
0,Arab States,708,70.9,12.4,8.0,13501
1,East Asia and the Pacific,749,75.6,13.8,7.8,15580
2,Europe and Central Asia,796,72.9,15.4,10.6,19352
3,Latin America and the Caribbean,754,72.1,14.8,9.0,14521
4,South Asia,632,67.9,11.6,6.7,6481
5,Sub-Saharan Africa,547,60.1,10.3,6.0,3699

In [64]:
pip install unidecode

Collecting unidecode
  Downloading Unidecode-1.3.8-py3-none-any.whl (235 kB)
     ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ 235.5/235.5 kB 1.9 MB/s eta 0:00:00
Installing collected packages: unidecode
Successfully installed unidecode-1.3.8

In [65]:
#Formateo de datos
#mayus a las regiones
from unidecode import unidecode

regionOK['Regions']=regionOK.Regions.apply(unidecode)
regionOK['Regions']=regionOK.Regions.str.upper()

#se formatea de object a int a GNI
regionOK['GNI']=pd.to_numeric(regionOK.GNI)
regionOK.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Regions          6 non-null      object
 1   HDI              6 non-null      int64
 2   life             6 non-null      float64
 3   years_schooling  6 non-null      float64
 4   Mean_schooling   6 non-null      float64
 5   GNI              6 non-null      int64
dtypes: float64(3), int64(2), object(1)
memory usage: 416.0+ bytes

In [66]:
regionOK.GNI.describe()

count        6.000000
mean     12189.000000
std       5909.794954
min       3699.000000
25%       8236.000000
50%      14011.000000
75%      15315.250000
max      19352.000000
Name: GNI, dtype: float64

# **9. Least Developed Countries**

In [67]:
LDC=pd.read_csv(url, skiprows=223, nrows=2)
LDC.drop(columns=['Unnamed: 0','Unnamed: 3', 'Unnamed: 5','Unnamed: 7','Unnamed: 9','Unnamed: 11', 'Unnamed: 12', 'Unnamed: 14','Unnamed: 13'], inplace = True)
LDC.columns = ['Country', 'HDI rank', 'Life_expectancy', 'years_schooling', 'mean_years_schooling', 'GNI']
LDC.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 6 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Country               2 non-null      object
 1   HDI rank              2 non-null      int64
 2   Life_expectancy       2 non-null      float64
 3   years_schooling       2 non-null      float64
 4   mean_years_schooling  2 non-null      float64
 5   GNI                   2 non-null      object
dtypes: float64(3), int64(1), object(2)
memory usage: 224.0+ bytes

In [68]:
LDC

,Country,HDI rank,Life_expectancy,years_schooling,mean_years_schooling,GNI
0,Least developed countries,540,64.2,10.2,5.2,"2,881"
1,Small island developing states,730,70.3,12.4,9.1,"16,782"

In [69]:
LDC['GNI'] = LDC['GNI'].str.replace(',','')
LDC['GNI']=pd.to_numeric(LDC.GNI)
LDC.describe()

,HDI rank,Life_expectancy,years_schooling,mean_years_schooling,GNI
count,2.000000,2.000000,2.000000,2.000000,2.000000
mean,635.000000,67.250000,11.300000,7.150000,9831.500000
std,134.350288,4.313351,1.555635,2.757716,9829.491365
min,540.000000,64.200000,10.200000,5.200000,2881.000000
25%,587.500000,65.725000,10.750000,6.175000,6356.250000
50%,635.000000,67.250000,11.300000,7.150000,9831.500000
75%,682.500000,68.775000,11.850000,8.125000,13306.750000
max,730.000000,70.300000,12.400000,9.100000,16782.000000

# **10. Organisation for Economic Co-operation and Development**

In [70]:
OECD=pd.read_csv(url, skiprows=226, nrows=1)
OECD.drop(columns=['Unnamed: 0','Unnamed: 2','Unnamed: 3','Unnamed: 5','Unnamed: 7','Unnamed: 8','Unnamed: 9','Unnamed: 11','Unnamed: 12','Unnamed: 13','Unnamed: 14'], inplace = True)
OECD.columns = ['Country', 'Life_expectancy', 'years_schooling', 'GNI']

OECD.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Country          1 non-null      object
 1   Life_expectancy  1 non-null      float64
 2   years_schooling  1 non-null      float64
 3   GNI              1 non-null      object
dtypes: float64(2), object(2)
memory usage: 160.0+ bytes

In [71]:
OECD['GNI'] = OECD['GNI'].str.replace(',','')
OECD['GNI']=pd.to_numeric(OECD.GNI)
OECD

,Country,Life_expectancy,years_schooling,GNI
0,Organisation for Economic Co-operation and Dev...,79.0,16.5,45087

# **11. World**

In [72]:
WORLD=pd.read_csv(url, skiprows=228, nrows=1)
WORLD.drop(columns=['Unnamed: 0','Unnamed: 2','Unnamed: 3','Unnamed: 5','Unnamed: 7','Unnamed: 8','Unnamed: 9','Unnamed: 11','Unnamed: 12','Unnamed: 13','Unnamed: 14'], inplace = True)
WORLD.columns = ['Country', 'Life_expectancy', 'years_schooling', 'GNI']
WORLD.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Country          1 non-null      object
 1   Life_expectancy  1 non-null      float64
 2   years_schooling  1 non-null      float64
 3   GNI              1 non-null      object
dtypes: float64(2), object(2)
memory usage: 160.0+ bytes

In [73]:
WORLD['GNI'] = WORLD['GNI'].str.replace(',','')
WORLD['GNI']=pd.to_numeric(WORLD.GNI)
WORLD

  Country  Life_expectancy  years_schooling    GNI
0   World             71.4             12.8  16752